### ISSUE TITLE
Confusion regarding difference in track structs

### ISSUE THREAD

**Issue by Theis194** [KOEGlike/rust_spotify_web_playback_sdk#2]
I have started using your crate and stumbled upon the difference in the track structs from web_playback::State::Track and state_change::StateChange:::Track one has duration the other doesn't, one has paused, and the other doesn't, is there a reason why one has a certain field and the other don't have the same field?

**Comment by KOEGlike** [comment]
Thanks for the report, one was implemented to the Spotify documentation spec, and one was to the object that the function returned, now there is one global track struct in the [new version](https://crates.io/crates/rust_spotify_web_playback_sdk/0.2.1)
